# Generated by Django 3.1 on 2021-10-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211024_1816'),
        ('accounts', '0006_auto_20211024_1900'),
    ]

    operations = [
    ]
