# Generated by Django 3.1 on 2021-10-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0002_auto_20211031_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabularies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=50, null=True)),
                ('definitions', models.JSONField(blank=True, null=True)),
                ('reading', models.JSONField(blank=True, null=True)),
                ('folders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folders')),
            ],
        ),
    ]
