# Generated by Django 3.2.8 on 2021-10-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabularies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=50, null=True)),
                ('meaning', models.CharField(max_length=50, null=True)),
                ('hiragana', models.CharField(max_length=50, null=True)),
                ('folders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folders')),
            ],
        ),
    ]
