# Generated by Django 3.1 on 2021-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='visibility',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
