# Generated by Django 3.1 on 2021-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20211031_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
