# Generated by Django 3.1 on 2021-11-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.topic'),
        ),
    ]
